#!/usr/bin/python

import os
import sys
import uuid
import subprocess
import urllib.parse
from crontab import CronTab
from crontab import CronSlices

PLAYER = "/usr/local/bin/mpg123"
SONG_DIR = "/data"
URI = "/cgi-bin/alarmclock.py"

cron = CronTab(user=True)

def parse_post_data():
    # generated by ChatGPT
    content_length = int(os.environ.get('CONTENT_LENGTH', 0))
    if content_length > 0:
        post_data = sys.stdin.read(content_length)
        parsed_data = urllib.parse.parse_qs(post_data)
        return parsed_data
    return {}

def generate_html():
    cron_list = "\n".join(f"""
      <form style='display: inline' method='post' action='?action=del'>
        <code>{j}</code>
        <button type='submit' name='delete' value='{j.comment}'>x</button>
        <br>
      </form>
    """ for j in cron)
    song_list = "\n".join(f"<option value='{s}'>{s}</option>" for s in os.listdir(SONG_DIR))
    html = f"""
<!doctype html>
<html>
  <head>
    <title>Alarm Clock</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <form style='display: inline' method='post' action='?action=pkill'>
      <button type='submit'>🗡</button>
      <br>
    </form>
    {cron_list}
    <form action="?action=add" method="post">
      <input type="text" name="cron">
      <select name="song">
    {song_list}
      </select>
      <input type="submit" value="+" name="type">
      <input type="submit" value="»" name="type">
    </form>
  </body>
</html>
    """
    return html

def redirect():
    print("Status: 302 Found")
    print(f"Location: {URI}")
    print("") 

def router():
    if os.getenv("REQUEST_METHOD") == "GET":
        print("Content-Type: text/html")
        print("")
        print(generate_html())
        
    elif os.getenv("REQUEST_METHOD") == "POST":
        action = urllib.parse.parse_qs(os.getenv("QUERY_STRING"))["action"][0] # TODO error handling
        form = parse_post_data()
        match action:
            case "add":
                time = form["cron"][0]
                song = form["song"][0]
                if time != None and song in os.listdir(SONG_DIR) and CronSlices.is_valid(time):
                    job = 0
                    if form["type"][0] == "+":
                        job = cron.new(command=f"-n {PLAYER} '{SONG_DIR}/{song}'", comment=str(uuid.uuid1()))
                    elif form["type"][0] == "»":
                        uid = str(uuid.uuid1())
                        job = cron.new(command=f"-n {__file__} '{SONG_DIR}/{song}' {uid}", comment=uid)

                    job.setall(time)
                    cron.write()
            case "del":
                uid = form["delete"][0]
                if uid != None:
                    job_iter = cron.find_comment(uid)
                    [cron.remove(j) for j in job_iter]
                    cron.write()
            case "pkill":
                subprocess.run(["pkill", os.path.basename(PLAYER)])
            case _:
                pass
        redirect()
    else:
        print("?")

def do_oneshot():
    song_with_dir = sys.argv[1]
    uid = sys.argv[2]
    job_iter = cron.find_comment(uid)
    [cron.remove(j) for j in job_iter]
    cron.write()
    subprocess.run([PLAYER, song_with_dir])


if len(sys.argv) < 2:
    router()
else:
    do_oneshot()
